# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kmoilane <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/01/22 21:46:43 by kmoilane          #+#    #+#              #
#    Updated: 2020/01/22 21:47:03 by kmoilane         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine

RUN sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install vim -y

CMD vim
