FROM debian

MAINTAINER Karri Moilanen <kmoilane@student.hive.fi>

RUN sudo apt-get update && sudo apt-get upgrade -y/
	sudo apt-get install wget bzip2 -y

RUN	wget http://dl.4players.de/ts/releases/3.0.13.8/teamspeak3-server_linux_amd64-3.0.13.8.tar.bz@s
RUN tar xfvj teamspeak3-server_linux_amd64-3.0.13.8.tar.bz2
